BOT_TOKEN: 
  - Nzk1MTk3ODA5NTk0NzI4NDY4.GTq6Mc.13BEixgocXDq2nIq9HtB5RmKwlmR7CzyrNe_p4
CHANNEL_ID: 
  - 1064892705001443379
  - 1065046724906848408
MODE: simsimi
REPLY: Y
SIMSIMI_LANG: en
DELAY: 10
DEL_AFTER: 
REPOST_LAST_CHAT: 100